# Generated by Django 5.1.6 on 2025-07-21 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_rename_hms_event_eventbooking_payment'),
        ('rooms', '0006_remove_roomimage_room_type_roomimage_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(null=True)),
                ('rating', models.IntegerField(default=1)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('event_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.eventbooking')),
                ('room_booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
