# Generated by Django 5.1.6 on 2025-08-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_banners_career_controlpanel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banners',
            table='banners',
        ),
    ]
