# Generated by Django 5.1.6 on 2025-07-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_gallery_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room_type',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype'),
        ),
    ]
